"""initial database migration

Revision ID: 5ffacf205a32
Revises: 
Create Date: 2021-05-10 21:49:18.847673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffacf205a32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('dose', sa.Float(), nullable=False),
    sa.Column('machine', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('harvest_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('time_to_harvest', sa.DateTime(), nullable=False),
    sa.Column('harvest_duration', sa.Integer(), nullable=False),
    sa.Column('expected_yield', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sow')
    op.drop_table('issue')
    op.drop_table('harvest')
    op.drop_table('application')
    op.drop_table('plot')
    # ### end Alembic commands ###
